In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Airlinedelaycause.csv")

In [4]:
df

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,12,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",72.0,5.0,2.46,1.00,...,0.00,0.81,0.0,0.0,672.0,61.0,574.0,20.0,0.0,17.0
1,2023,12,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,7.0,4.25,0.00,...,0.00,1.75,0.0,0.0,348.0,252.0,0.0,33.0,0.0,63.0
2,2023,12,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",95.0,10.0,5.94,0.00,...,0.00,3.00,0.0,0.0,859.0,536.0,0.0,47.0,0.0,276.0
3,2023,12,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",23.0,2.0,0.56,0.00,...,0.00,1.44,1.0,0.0,75.0,9.0,0.0,0.0,0.0,66.0
4,2023,12,9E,Endeavor Air Inc.,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2111.0,256.0,76.88,8.75,...,0.00,117.94,1.0,0.0,21424.0,8906.0,732.0,1487.0,0.0,10299.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179333,2015,1,WN,Southwest Airlines Co.,ONT,"Ontario, CA: Ontario International",892.0,184.0,59.21,2.61,...,0.98,98.79,3.0,2.0,8431.0,2661.0,123.0,1029.0,92.0,4526.0
179334,2015,1,WN,Southwest Airlines Co.,ORF,"Norfolk, VA: Norfolk International",151.0,45.0,18.00,2.01,...,0.00,17.80,0.0,0.0,2391.0,840.0,295.0,301.0,0.0,955.0
179335,2015,1,WN,Southwest Airlines Co.,PBI,"West Palm Beach/Palm Beach, FL: Palm Beach Int...",251.0,68.0,25.17,0.08,...,0.00,27.83,6.0,0.0,3405.0,1003.0,9.0,534.0,0.0,1859.0
179336,2015,1,WN,Southwest Airlines Co.,PDX,"Portland, OR: Portland International",793.0,173.0,64.00,1.27,...,0.00,86.60,0.0,1.0,7479.0,2370.0,143.0,689.0,0.0,4277.0
179337,2015,1,WN,Southwest Airlines Co.,PHL,"Philadelphia, PA: Philadelphia International",773.0,172.0,45.62,13.62,...,0.00,65.67,50.0,3.0,9475.0,2818.0,890.0,2352.0,0.0,3415.0

In [5]:
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,12,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",72.0,5.0,2.46,1.00,...,0.0,0.81,0.0,0.0,672.0,61.0,574.0,20.0,0.0,17.0
1,2023,12,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,7.0,4.25,0.00,...,0.0,1.75,0.0,0.0,348.0,252.0,0.0,33.0,0.0,63.0
2,2023,12,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",95.0,10.0,5.94,0.00,...,0.0,3.00,0.0,0.0,859.0,536.0,0.0,47.0,0.0,276.0
3,2023,12,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",23.0,2.0,0.56,0.00,...,0.0,1.44,1.0,0.0,75.0,9.0,0.0,0.0,0.0,66.0
4,2023,12,9E,Endeavor Air Inc.,ATL,"Atlanta, GA: Hartsfield-Jackson Atlanta Intern...",2111.0,256.0,76.88,8.75,...,0.0,117.94,1.0,0.0,21424.0,8906.0,732.0,1487.0,0.0,10299.0

In [6]:
df['carrier'].unique()

array(['9E', 'AA', 'OH', 'OO', 'WN', 'AS', 'DL', 'PT', 'QX', 'UA', 'YV',
       'B6', 'F9', 'G4', 'G7', 'HA', 'MQ', 'YX', 'ZW', 'C5', 'NK', 'EM',
       'EV', 'AX', 'CP', 'KS', '9K', 'VX', 'US'], dtype=object)

In [7]:
df['carrier'].unique().size

29

In [8]:
df['carrier_name'].unique()

array(['Endeavor Air Inc.', 'American Airlines Network',
       'PSA Airlines Inc.', 'SkyWest Airlines Inc.', 'Southwest Airlines',
       'Alaska Airlines Network', 'Delta Air Lines Network',
       'Piedmont Airlines', 'Horizon Air', 'United Air Lines Network',
       'Mesa Airlines Inc.', 'JetBlue Airways', 'Frontier Airlines',
       'Allegiant Air', 'GoJet Airlines LLC d/b/a United Express',
       'Hawaiian Airlines Network', 'Envoy Air', 'Republic Airline',
       'Air Wisconsin Airlines Corp', 'CommuteAir LLC dba CommuteAir',
       'Spirit Airlines', 'Commutair Aka Champlain Enterprises, Inc.',
       'Empire Airlines Inc.', 'ExpressJet Airlines LLC',
       'Trans States Airlines', 'Compass Airlines',
       'Peninsula Airways Inc.', 'ExpressJet Airlines Inc.', 'Cape Air',
       'Virgin America', 'American Airlines Inc.', 'Alaska Airlines Inc.',
       'Delta Air Lines Inc.', 'United Air Lines Inc.',
       'Southwest Airlines Co.', 'Frontier Airlines Inc.',
       'Hawaiian Airlines Inc.', 'Spirit Air Lines', 'US Airways Inc.'],
      dtype=object)

In [9]:
df['carrier_name'].unique().size

39

In [10]:
df.groupby(['carrier', 'carrier_name']).count()

                                                    year  month  airport  \
carrier carrier_name
9E      Endeavor Air Inc.                           7494   7494     7494
9K      Cape Air                                      15     15       15
AA      American Airlines Inc.                      3258   3258     3258
        American Airlines Network                   7654   7654     7654
AS      Alaska Airlines Inc.                        2321   2321     2321
        Alaska Airlines Network                     5433   5433     5433
AX      Trans States Airlines                       1932   1932     1932
B6      JetBlue Airways                             6827   6827     6827
C5      Commutair Aka Champlain Enterprises, Inc.   2646   2646     2646
        CommuteAir LLC dba CommuteAir                784    784      784
CP      Compass Airlines                             926    926      926
DL      Delta Air Lines Inc.                        5303   5303     5303
        Delta Air Lines Network                     9677   9677     9677
EM      Empire Airlines Inc.                         144    144      144
EV      ExpressJet Airlines Inc.                    7348   7348     7348
        ExpressJet Airlines LLC                     1445   1445     1445
F9      Frontier Airlines                           6438   6438     6438
        Frontier Airlines Inc.                      1869   1869     1869
G4      Allegiant Air                               8761   8761     8761
G7      GoJet Airlines LLC d/b/a United Express     3948   3948     3948
HA      Hawaiian Airlines Inc.                       612    612      612
        Hawaiian Airlines Network                   1340   1340     1340
KS      Peninsula Airways Inc.                        44     44       44
MQ      Envoy Air                                  11299  11299    11299
NK      Spirit Air Lines                            1257   1257     1257
        Spirit Airlines                             3693   3693     3693
OH      PSA Airlines Inc.                           6545   6545     6545
OO      SkyWest Airlines Inc.                      23821  23821    23821
PT      Piedmont Airlines                           4160   4160     4160
QX      Horizon Air                                 3203   3203     3203
UA      United Air Lines Inc.                       3147   3147     3147
        United Air Lines Network                    7271   7271     7271
US      US Airways Inc.                              434    434      434
VX      Virgin America                               821    821      821
WN      Southwest Airlines                          6941   6941     6941
        Southwest Airlines Co.                      3110   3110     3110
YV      Mesa Airlines Inc.                          6877   6877     6877
YX      Republic Airline                            6072   6072     6072
ZW      Air Wisconsin Airlines Corp                 4468   4468     4468

                                                   airport_name  arr_flights  \
carrier carrier_name
9E      Endeavor Air Inc.                                  7494         7469
9K      Cape Air                                             15           15
AA      American Airlines Inc.                             3258         3258
        American Airlines Network                          7654         7653
AS      Alaska Airlines Inc.                               2321         2321
        Alaska Airlines Network                            5433         5432
AX      Trans States Airlines                              1932         1909
B6      JetBlue Airways                                    6827         6827
C5      Commutair Aka Champlain Enterprises, Inc.          2646         2631
        CommuteAir LLC dba CommuteAir                       784          778
CP      Compass Airlines                                    926          923
DL      Delta Air Lines Inc.                               5303         5291
        Delta Air Lines Network                            9677         9646
EM      Empire Airlines Inc.                                144          144
EV      ExpressJet Airlines Inc.                           7348         7333
        ExpressJet Airlines LLC                            1445         1433
F9      Frontier Airlines                                  6438         6436
        Frontier Airlines Inc.                             1869         1869
G4      Allegiant Air                                      8761         8760
G7      GoJet Airlines LLC d/b/a United Express            3948         3922
HA      Hawaiian Airlines Inc.                              612          612
        Hawaiian Airlines Network                          1340         1340
KS      Peninsula Airways Inc.                               44           44
MQ      Envoy Air                                         11299        11282
NK      Spirit Air Lines                                   1257         1257
        Spirit Airlines                                    3693         3693
OH      PSA Airlines Inc.                                  6545         6543
OO      SkyWest Airlines Inc.                             23821        23771
PT      Piedmont Airlines                                  4160         4155
QX      Horizon Air                                        3203         3200
UA      United Air Lines Inc.                              3147         3145
        United Air Lines Network                           7271         7262
US      US Airways Inc.                                     434          434
VX      Virgin America                                      821          819
WN      Southwest Airlines                                 6941         6941
        Southwest Airlines Co.                             3110         3110
YV      Mesa Airlines Inc.                                 6877         6843
YX      Republic Airline                                   6072         6052
ZW      Air Wisconsin Airlines Corp                        4468         4444

                                                   arr_del15  carrier_ct  \
carrier carrier_name
9E      Endeavor Air Inc.                               7450        7469
9K      Cape Air                                          15          15
AA      American Airlines Inc.                          3257        3258
        American Airlines Network                       7649        7653
AS      Alaska Airlines Inc.                            2321        2321
        Alaska Airlines Network                         5431        5432
AX      Trans States Airlines                           1905        1909
B6      JetBlue Airways                                 6822        6827
C5      Commutair Aka Champlain Enterprises, Inc.       2620        2631
        CommuteAir LLC dba CommuteAir                    777         778
CP      Compass Airlines                                 916         923
DL      Delta Air Lines Inc.                            5291        5291
        Delta Air Lines Network                         9637        9646
EM      Empire Airlines Inc.                             144         144
EV      ExpressJet Airlines Inc.                        7325        7333
        ExpressJet Airlines LLC                         1427        1433
F9      Frontier Airlines                               6426        6436
        Frontier Airlines Inc.                          1869        1869
G4      Allegiant Air                                   8698        8760
G7      GoJet Airlines LLC d/b/a United Express         3912        3922
HA      Hawaiian Airlines Inc.                           612         612
        Hawaiian Airlines Network                       1339        1340
KS      Peninsula Airways Inc.                            44          44
MQ      Envoy Air                                      11271       11282
NK      Spirit Air Lines                                1257        1257
        Spirit Airlines                                 3684        3693
OH      PSA Airlines Inc.                               6537        6543
OO      SkyWest Airlines Inc.                          23756       23771
PT      Piedmont Airlines                               4148        4155
QX      Horizon Air                                     3200        3200
UA      United Air Lines Inc.                           3144        3145
        United Air Lines Network                        7251        7262
US      US Airways Inc.                                  434         434
VX      Virgin America                                   818         819
WN      Southwest Airlines                              6941        6941
        Southwest Airlines Co.                          3110        3110
YV      Mesa Airlines Inc.                              6830        6843
YX      Republic Airline                                6045        6052
ZW      Air Wisconsin Airlines Corp                     4434        4444

                                                   weather_ct  nas_ct  \
carrier carrier_name
9E      Endeavor Air Inc.                                7469    7469
9K      Cape Air                                           15      15
AA      American Airlines Inc.                           3258    3258
        American Airlines Network                        7653    7653
AS      Alaska Airlines Inc.                             2321    2321
        Alaska Airlines Network                          5432    5432
AX      Trans States Airlines                            1909    1909
B6      JetBlue Airways                                  6827    6827
C5      Commutair Aka Champlain Enterprises, Inc.        2631    2631
        CommuteAir LLC dba CommuteAir                     778     778
CP      Compass Airlines                                  923     923
DL      Delta Air Lines Inc.                             5291    5291
        Delta Air Lines Network                          9646    9646
EM      Empire Airlines Inc.                              144     144
EV      ExpressJet Airlines Inc.                         7333    7333
        ExpressJet Airlines LLC                          1433    1433
F9      Frontier Airlines                                6436    6436
        Frontier Airlines Inc.                           1869    1869
G4      Allegiant Air                                    8760    8760
G7      GoJet Airlines LLC d/b/a United Express          3922    3922
HA      Hawaiian Airlines Inc.                            612     612
        Hawaiian Airlines Network                        1340    1340
KS      Peninsula Airways Inc.                             44      44
MQ      Envoy Air                                       11282   11282
NK      Spirit Air Lines                                 1257    1257
        Spirit Airlines                                  3693    3693
OH      PSA Airlines Inc.                                6543    6543
OO      SkyWest Airlines Inc.                           23771   23771
PT      Piedmont Airlines                                4155    4155
QX      Horizon Air                                      3200    3200
UA      United Air Lines Inc.                            3145    3145
        United Air Lines Network                         7262    7262
US      US Airways Inc.                                   434     434
VX      Virgin America                                    819     819
WN      Southwest Airlines                               6941    6941
        Southwest Airlines Co.                           3110    3110
YV      Mesa Airlines Inc.                               6843    6843
YX      Republic Airline                                 6052    6052
ZW      Air Wisconsin Airlines Corp                      4444    4444

                                                   security_ct  \
carrier carrier_name
9E      Endeavor Air Inc.                                 7469
9K      Cape Air                                            15
AA      American Airlines Inc.                            3258
        American Airlines Network                         7653
AS      Alaska Airlines Inc.                              2321
        Alaska Airlines Network                           5432
AX      Trans States Airlines                             1909
B6      JetBlue Airways                                   6827
C5      Commutair Aka Champlain Enterprises, Inc.         2631
        CommuteAir LLC dba CommuteAir                      778
CP      Compass Airlines                                   923
DL      Delta Air Lines Inc.                              5291
        Delta Air Lines Network                           9646
EM      Empire Airlines Inc.                               144
EV      ExpressJet Airlines Inc.                          7333
        ExpressJet Airlines LLC                           1433
F9      Frontier Airlines                                 6436
        Frontier Airlines Inc.                            1869
G4      Allegiant Air                                     8760
G7      GoJet Airlines LLC d/b/a United Express           3922
HA      Hawaiian Airlines Inc.                             612
        Hawaiian Airlines Network                         1340
KS      Peninsula Airways Inc.                              44
MQ      Envoy Air                                        11282
NK      Spirit Air Lines                                  1257
        Spirit Airlines                                   3693
OH      PSA Airlines Inc.                                 6543
OO      SkyWest Airlines Inc.                            23771
PT      Piedmont Airlines                                 4155
QX      Horizon Air                                       3200
UA      United Air Lines Inc.                             3145
        United Air Lines Network                          7262
US      US Airways Inc.                                    434
VX      Virgin America                                     819
WN      Southwest Airlines                                6941
        Southwest Airlines Co.                            3110
YV      Mesa Airlines Inc.                                6843
YX      Republic Airline                                  6052
ZW      Air Wisconsin Airlines Corp                       4444

                                                   late_aircraft_ct  \
carrier carrier_name
9E      Endeavor Air Inc.                                      7469
9K      Cape Air                                                 15
AA      American Airlines Inc.                                 3258
        American Airlines Network                              7653
AS      Alaska Airlines Inc.                                   2321
        Alaska Airlines Network                                5432
AX      Trans States Airlines                                  1909
B6      JetBlue Airways                                        6827
C5      Commutair Aka Champlain Enterprises, Inc.              2631
        CommuteAir LLC dba CommuteAir                           778
CP      Compass Airlines                                        923
DL      Delta Air Lines Inc.                                   5291
        Delta Air Lines Network                                9646
EM      Empire Airlines Inc.                                    144
EV      ExpressJet Airlines Inc.                               7333
        ExpressJet Airlines LLC                                1433
F9      Frontier Airlines                                      6436
        Frontier Airlines Inc.                                 1869
G4      Allegiant Air                                          8760
G7      GoJet Airlines LLC d/b/a United Express                3922
HA      Hawaiian Airlines Inc.                                  612
        Hawaiian Airlines Network                              1340
KS      Peninsula Airways Inc.                                   44
MQ      Envoy Air                                             11282
NK      Spirit Air Lines                                       1257
        Spirit Airlines                                        3693
OH      PSA Airlines Inc.                                      6543
OO      SkyWest Airlines Inc.                                 23771
PT      Piedmont Airlines                                      4155
QX      Horizon Air                                            3200
UA      United Air Lines Inc.                                  3145
        United Air Lines Network                               7262
US      US Airways Inc.                                         434
VX      Virgin America                                          819
WN      Southwest Airlines                                     6941
        Southwest Airlines Co.                                 3110
YV      Mesa Airlines Inc.                                     6843
YX      Republic Airline                                       6052
ZW      Air Wisconsin Airlines Corp                            4444

                                                   arr_cancelled  \
carrier carrier_name
9E      Endeavor Air Inc.                                   7469
9K      Cape Air                                              15
AA      American Airlines Inc.                              3258
        American Airlines Network                           7653
AS      Alaska Airlines Inc.                                2321
        Alaska Airlines Network                             5432
AX      Trans States Airlines                               1909
B6      JetBlue Airways                                     6827
C5      Commutair Aka Champlain Enterprises, Inc.           2631
        CommuteAir LLC dba CommuteAir                        778
CP      Compass Airlines                                     923
DL      Delta Air Lines Inc.                                5291
        Delta Air Lines Network                             9646
EM      Empire Airlines Inc.                                 144
EV      ExpressJet Airlines Inc.                            7333
        ExpressJet Airlines LLC                             1433
F9      Frontier Airlines                                   6436
        Frontier Airlines Inc.                              1869
G4      Allegiant Air                                       8760
G7      GoJet Airlines LLC d/b/a United Express             3922
HA      Hawaiian Airlines Inc.                               612
        Hawaiian Airlines Network                           1340
KS      Peninsula Airways Inc.                                44
MQ      Envoy Air                                          11282
NK      Spirit Air Lines                                    1257
        Spirit Airlines                                     3693
OH      PSA Airlines Inc.                                   6543
OO      SkyWest Airlines Inc.                              23771
PT      Piedmont Airlines                                   4155
QX      Horizon Air                                         3200
UA      United Air Lines Inc.                               3145
        United Air Lines Network                            7262
US      US Airways Inc.                                      434
VX      Virgin America                                       819
WN      Southwest Airlines                                  6941
        Southwest Airlines Co.                              3110
YV      Mesa Airlines Inc.                                  6843
YX      Republic Airline                                    6052
ZW      Air Wisconsin Airlines Corp                         4444

                                                   arr_diverted  arr_delay  \
carrier carrier_name
9E      Endeavor Air Inc.                                  7469       7469
9K      Cape Air                                             15         15

In [11]:
df['airport'].unique().size

396

In [12]:
df['airport_name'].unique().size

420

In [13]:
idx = df.index[df['carrier'] == 'AA']

In [14]:
idx

Index([   110,    111,    112,    113,    114,    115,    116,    117,    118,
          119,
       ...
       178234, 178235, 178236, 178237, 178238, 178239, 178240, 178241, 178242,
       178243],
      dtype='int64', length=10912)

In [15]:
df['carrier_name'].loc[idx].unique()

array(['American Airlines Network', 'American Airlines Inc.'],
      dtype=object)

In [17]:
df.isna()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179333,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
179334,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
179335,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
179336,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
179337,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [18]:
df.isnull()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179333,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
179334,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
179335,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
179336,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
179337,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
df.size

3766098

In [20]:
df.shape

(179338, 21)

In [31]:
df[df['arr_del15'].isnull()]

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
779,2023,12,UA,United Air Lines Network,BHM,"Birmingham, AL: Birmingham-Shuttlesworth Inter...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1254,2023,12,G7,GoJet Airlines LLC d/b/a United Express,SBN,"South Bend, IN: South Bend International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1423,2023,12,YV,Mesa Airlines Inc.,ROA,"Roanoke, VA: Roanoke Blacksburg Regional",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1470,2023,12,YX,Republic Airline,ICT,"Wichita, KS: Wichita Dwight D Eisenhower National",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2278,2023,11,C5,CommuteAir LLC dba CommuteAir,BTV,"Burlington, VT: Burlington International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176507,2015,3,MQ,Envoy Air,GUC,"Gunnison, CO: Gunnison-Crested Butte Regional",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
176725,2015,3,OO,SkyWest Airlines Inc.,EWR,"Newark, NJ: Newark Liberty International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176825,2015,3,UA,United Air Lines Inc.,STL,"St. Louis, MO: St Louis Lambert International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178668,2015,1,EV,ExpressJet Airlines Inc.,PHX,"Phoenix, AZ: Phoenix Sky Harbor International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179059,2015,1,OO,SkyWest Airlines Inc.,EVV,"Evansville, IN: Evansville Regional",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
df.iloc[779]

year                                                                2023
month                                                                 12
carrier                                                               UA
carrier_name                                    United Air Lines Network
airport                                                              BHM
airport_name           Birmingham, AL: Birmingham-Shuttlesworth Inter...
arr_flights                                                          NaN
arr_del15                                                            NaN
carrier_ct                                                           NaN
weather_ct                                                           NaN
nas_ct                                                               NaN
security_ct                                                          NaN
late_aircraft_ct                                                     NaN
arr_cancelled                                                        NaN
arr_diverted                                                         NaN
arr_delay                                                            NaN
carrier_delay                                                        NaN
weather_delay                                                        NaN
nas_delay                                                            NaN
security_delay                                                       NaN
late_aircraft_delay                                                  NaN
Name: 779, dtype: object